version: '3.7'


services:
  solr:
    image: dina/solr:v0.3
    container_name: solr
    restart: always
    environment:
      SOLR_JAVA_MEM: -Xms2g -Xmx2g
      LOG4J_PROPS: /var/solr/log4j.properties
    ports:
      - 18983:8983
    volumes:
      - ./log4j.properties:/var/solr/log4j.properties
      - ./solr8/mycores:/var/solr/data
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - samlingar

volumes:
  data:

